In [1]:

'''nltk.download('wordnet')
nltk.download('averagded_perseptron_tagger')
nltk.download('stopwords')
nltk.download('punkt')'''


"nltk.download('wordnet')\nnltk.download('averagded_perseptron_tagger')\nnltk.download('stopwords')\nnltk.download('punkt')"

In [2]:
#first we will install nltk library
#!pip install nltk

In [3]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv(r"C:\Users\pooja\Desktop\All guvi projects\final_project\FinalBalancedDataset.csv")
df.head(12)

Unnamed: 0  Toxicity                                              tweet
0            0         0   @user when a father is dysfunctional and is s...
1            1         0  @user @user thanks for #lyft credit i can't us...
2            2         0                                bihday your majesty
3            3         0  #model   i love u take with u all the time in ...
4            4         0             factsguide: society now    #motivation
5            5         0  [2/2] huge fan fare and big talking before the...
6            6         0   @user camping tomorrow @user @user @user @use...
7            7         0  the next school year is the year for exams.ðŸ˜...
8            8         0  we won!!! love the land!!! #allin #cavs #champ...
9            9         0   @user @user welcome here !  i'm   it's so #gr...
10          10         0   ↝ #ireland consumer price index (mom) climb...
11          11         0  we are so selfish. #orlando #standwithorlando ...

In [5]:
df.iloc[4,:]

Unnamed: 0                                          4
Toxicity                                            0
tweet          factsguide: society now    #motivation
Name: 4, dtype: object

In [6]:
df.columns

Index(['Unnamed: 0', 'Toxicity', 'tweet'], dtype='object')

In [7]:
del df['Unnamed: 0']

In [8]:
df

Toxicity                                              tweet
0             0   @user when a father is dysfunctional and is s...
1             0  @user @user thanks for #lyft credit i can't us...
2             0                                bihday your majesty
3             0  #model   i love u take with u all the time in ...
4             0             factsguide: society now    #motivation
...         ...                                                ...
56740         1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
56741         1  you've gone and broke the wrong heart baby, an...
56742         1  young buck wanna eat!!.. dat nigguh like I ain...
56743         1              youu got wild bitches tellin you lies
56744         0  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[56745 rows x 2 columns]

In [9]:
df["tweet"].head()

0     @user when a father is dysfunctional and is s...
1    @user @user thanks for #lyft credit i can't us...
2                                  bihday your majesty
3    #model   i love u take with u all the time in ...
4               factsguide: society now    #motivation
Name: tweet, dtype: object

In [10]:
#importing nltk
import nltk
import re
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
ps=PorterStemmer()

In [11]:
corpus=[]
for i in range(len(df)):
    rp=re.sub('[^a-zA]'," ",df["tweet"][i])
    rp=rp.lower()
    rp=rp.split()
    rp=[ps.stem(word) for word in rp if not word in set(stopwords.words("english"))]
    rp=" ".join(rp)
    corpus.append(rp)

#### Bag OF words

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
ifidf=TfidfVectorizer()
tf=ifidf.fit_transform(corpus).toarray

### Vectorization

In [13]:
#!pip install sklearn

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(corpus)

In [15]:
y=pd.get_dummies(df["Toxicity"],drop_first=True)

### Train test split

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=80,random_state=56)

### Modeling

#### navie bayes classifier with default parameters

In [17]:
from sklearn.naive_bayes import MultinomialNB
model1=MultinomialNB()
model1.fit(x_train,y_train)

MultinomialNB()

### Prediction

In [18]:
ypred_test=model1.predict(x_test)
ypred_train=model1.predict(x_train)

### Evaluation

In [24]:
from sklearn.metrics import accuracy_score,r2_score,f1_score,precision_score,recall_score
print("Train Acuuracy:",accuracy_score(y_train,ypred_train))
print("Test Acuuracy:",accuracy_score(y_test,ypred_test))
print("r2_score:",r2_score(y_test,ypred_test))
print("f1_score:",f1_score(y_test,ypred_test))
print("precision_score:",precision_score(y_test,ypred_test))
print("recall_score:",recall_score(y_test,ypred_test))

Train Acuuracy: 0.9393629224388953
Test Acuuracy: 0.95
r2_score: 0.797979797979798
f1_score: 0.9473684210526316
precision_score: 0.9
recall_score: 1.0


In [25]:
from sklearn.metrics import confusion_matrix
model1=confusion_matrix(y_test,ypred_test)
model1

array([[40,  4],
       [ 0, 36]], dtype=int64)

### DecesionTreeClassifier

In [26]:
from sklearn.tree import DecisionTreeClassifier
model2=DecisionTreeClassifier()
model2.fit(x_train,y_train)

DecisionTreeClassifier()

In [27]:
ypred_test=model2.predict(x_test)
ypred_train=model2.predict(x_train)

In [28]:
from sklearn.metrics import accuracy_score,r2_score,f1_score,precision_score,recall_score
print("Train Acuuracy:",accuracy_score(y_train,ypred_train))
print("Test Acuuracy:",accuracy_score(y_test,ypred_test))
print("r2_score:",r2_score(y_test,ypred_test))
print("f1_score:",f1_score(y_test,ypred_test))
print("precision_score:",precision_score(y_test,ypred_test))
print("recall_score:",recall_score(y_test,ypred_test))

Train Acuuracy: 0.999717638754081
Test Acuuracy: 0.9375
r2_score: 0.7474747474747475
f1_score: 0.9333333333333333
precision_score: 0.8974358974358975
recall_score: 0.9722222222222222


 ### ROCAUC

In [29]:
from sklearn.linear_model import RidgeClassifier
from yellowbrick.classifier import ROCAUC
model2 = RidgeClassifier()
visualizer = ROCAUC(model2, classes=["win", "loss", "draw"])
visualizer.fit(x_train, y_train)        # Fit the training data to the visualizer
visualizer.score(x_test, y_test)        # Evaluate the model on the test data
visualizer.show()   

ModelError: no curves will be drawn; set binary=True.

In [24]:
from sklearn.metrics import confusion_matrix
model2=confusion_matrix(y_test,ypred_test)
model2

array([[41,  3],
       [ 1, 35]], dtype=int64)

### KNN(k nearest neighbur)

In [25]:
from sklearn.neighbors import KNeighborsClassifier
model3=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
model3.fit(x_train,y_train)

KNeighborsClassifier()

In [26]:
ypred_test=model3.predict(x_test)
ypred_train=model3.predict(x_train)

In [27]:
from sklearn.metrics import accuracy_score,r2_score,f1_score,precision_score,recall_score
print("Train Acuuracy:",accuracy_score(y_train,ypred_train))
print("Test Acuuracy:",accuracy_score(y_test,ypred_test))
print("r2_score:",r2_score(y_test,ypred_test))
print("f1_score:",f1_score(y_test,ypred_test))
print("precision_score:",precision_score(y_test,ypred_test))
print("recall_score:",recall_score(y_test,ypred_test))

Train Acuuracy: 0.9272566840201183
Test Acuuracy: 0.95
r2_score: 0.797979797979798
f1_score: 0.9411764705882353
precision_score: 1.0
recall_score: 0.8888888888888888


### confusion matrix

In [28]:
from sklearn.metrics import confusion_matrix
model3=confusion_matrix(y_test,ypred_test)
model3

array([[44,  0],
       [ 4, 32]], dtype=int64)

In [29]:
from sklearn.preprocessing import StandardScaler #scaling is not menadetry for decision tree or random forest
std=StandardScaler()
#x_train=std.fit_transform(x_train)
#x_test=std.transform(x_test)

In [30]:
#from sklearn.metrics import accuracy_score,f1_score,roc_curve,roc_auc_score

In [31]:
#print(f1_score)

### Random Forest Classifier

In [32]:
from sklearn.ensemble import RandomForestClassifier
model4= RandomForestClassifier(n_estimators=100,max_depth=3,max_features="sqrt")
model4.fit(x_train,y_train) #n_estimators=100 means combinding 100 dt

ypred_test=model4.predict(x_test)
ypred_train=model4.predict(x_train)

from sklearn.metrics import accuracy_score,r2_score,f1_score,precision_score,recall_score
print("Train Acuuracy:",accuracy_score(y_train,ypred_train))
print("Test Acuuracy:",accuracy_score(y_test,ypred_test))
print("r2_score:",r2_score(y_test,ypred_test))
print("f1_score:",f1_score(y_test,ypred_test))
print("precision_score:",precision_score(y_test,ypred_test))
print("recall_score:",recall_score(y_test,ypred_test))

Train Acuuracy: 0.5743933645107209
Test Acuuracy: 0.55
r2_score: -0.8181818181818179
f1_score: 0.0
precision_score: 0.0
recall_score: 0.0


In [ ]:
from sklearn.linear_model import RidgeClassifier
from yellowbrick.classifier import ROCAUC
model = RidgeClassifier()
visualizer = ROCAUC(model, classes=["win", "loss", "draw"])
visualizer.fit(X_train, y_train)        # Fit the training data to the visualizer
visualizer.score(X_test, y_test)        # Evaluate the model on the test data
visualizer.show()                       # Finalize and render the figure

### SVM(SUPPORT VECTORE MACHINES)

In [33]:
#modelling
from sklearn.svm import SVC
model5= SVC()
model5.fit(x_train,y_train)

#prediction
ypred_test=model5.predict(x_test)
ypred_train=model5.predict(x_train)

#accuracy
from sklearn.metrics import accuracy_score,r2_score,f1_score,precision_score,recall_score
print("Train Acuuracy:",accuracy_score(y_train,ypred_train))
print("Test Acuuracy:",accuracy_score(y_test,ypred_test))
print("r2_score:",r2_score(y_test,ypred_test))
print("f1_score:",f1_score(y_test,ypred_test))
print("precision_score:",precision_score(y_test,ypred_test))
print("recall_score:",recall_score(y_test,ypred_test))


Train Acuuracy: 0.9827230212653313
Test Acuuracy: 0.975
r2_score: 0.898989898989899
f1_score: 0.9722222222222222
precision_score: 0.9722222222222222
recall_score: 0.9722222222222222


### HYPERPARAMETER TUNING

In [ ]:
from sklearn.model_selection import GridSearchCV
estimator=SVC()
#param_grid={'C':[0.01,0.1,10,100],"kernel":["linear","rbf","sigmoid","poly"]}
grid=GridSearchCV(estimator,param_grid,cv=5)
grid.fit(x,y)

In [ ]:
grid.best_params_

### Rebuilding the SVM model with best parameters

In [35]:
model5=SVC(kernel="linear",C=1)
model5.fit(x_train,y_train)


y_pred_test=model4.predict(x_test)
y_pred_train=model4.predict(x_train)

#accuracy
from sklearn.metrics import accuracy_score,r2_score,f1_score,precision_score,recall_score
print("Train Acuuracy:",accuracy_score(y_train,ypred_train))
print("Test Acuuracy:",accuracy_score(y_test,ypred_test))
print("r2_score:",r2_score(y_test,ypred_test))
print("f1_score:",f1_score(y_test,ypred_test))
print("precision_score:",precision_score(y_test,ypred_test))
print("recall_score:",recall_score(y_test,ypred_test))

Train Acuuracy: 0.9827230212653313
Test Acuuracy: 0.975
r2_score: 0.898989898989899
f1_score: 0.9722222222222222
precision_score: 0.9722222222222222
recall_score: 0.9722222222222222


In [ ]:
# we can not use for xgbootsclassifier i think,it is xgboostregressior

In [ ]:
#import xgboost as xgb

In [ ]:
#from sklearn.model_selection import cross_val_score
#for lr in [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]:
    #model5=xgb.XGBClassifier(learning_rate=lr,n_estimatores=100,verbosity=0)
    #mdel5.fit(x_train,y_train)
    #model5.score(x_train,y_train)

In [ ]:
#model5=xgb.XGBClassifier(learning_rate=0.05,n_estimatores=100,verbosity=0)
#mdel5.fit(x_train,y_train)
#model5.score(x_train,y_train)